/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactInquiry {
  'id' : bigint,
  'name' : string,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface PortfolioItem {
  'id' : bigint,
  'title' : string,
  'displayOrder' : bigint,
  'createdAt' : bigint,
  'imageUrl' : string,
  'caption' : string,
  'category' : string,
}
export interface Testimonial {
  'id' : bigint,
  'clientName' : string,
  'reviewText' : string,
  'isActive' : boolean,
  'rating' : bigint,
  'location' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPortfolioItem' : ActorMethod<
    [string, string, string, string, bigint],
    bigint
  >,
  'addTestimonial' : ActorMethod<
    [string, string, bigint, string, boolean],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deletePortfolioItem' : ActorMethod<[bigint], undefined>,
  'deleteTestimonial' : ActorMethod<[bigint], undefined>,
  'getActiveTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getAllInquiries' : ActorMethod<[], Array<ContactInquiry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPortfolioItems' : ActorMethod<[], Array<PortfolioItem>>,
  'getSiteStats' : ActorMethod<[], Array<[string, bigint]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markInquiryRead' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedInitialData' : ActorMethod<[], undefined>,
  'submitInquiry' : ActorMethod<[string, string, string], bigint>,
  'updatePortfolioItem' : ActorMethod<
    [bigint, string, string, string, string, bigint],
    undefined
  >,
  'updateStat' : ActorMethod<[string, bigint], undefined>,
  'updateTestimonial' : ActorMethod<
    [bigint, string, string, bigint, string, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];